version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "willguibr"
      
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "willguibr"
