---
# zpa_segment_group_info.yml - Get details (ID and/or Name) of a segment group.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_segment_group' module to create a Segment Group in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables connection
# to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id. These may be defined as host variables
# (see `host_vars/zpa_cloud.yml` for an example) or extra vars.
#
# Modules Used
# ============
#
# zpa_segment_group_info - https://willguibr.github.io/zpacloud-ansible/modules/zpa_segment_group_info.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_segment_group_info.yml

- hosts: localhost
  connection: local

  tasks:
    - name: Gather Detail Information of All Segment Groups
      willguibr.zpacloud.zpa_segment_group_info:
      register: segment_groups

    - name: segment_groups
      debug:
        msg: "{{ segment_groups }}"

    - name: Gather Details of All Segment Groups by Name
      willguibr.zpacloud.zpa_segment_group_info:
        name: Example
      register: segment_group_name

    - name: segment_group_name
      debug:
        msg: "{{ segment_group_name }}"

    - name: Gather Details of All Segment Groups by ID
      willguibr.zpacloud.zpa_segment_group_info:
        id: "216196257331291969"
      register: segment_group_id

    - name: segment_group_id
      debug:
        msg: "{{ segment_group_id }}"
