---
# zpa_application_segment.yml - Create/Update/Delete an Application Segment.
#
# Description
# ===========
#
# Quick examples of how to use the 'zpa_application_segment' module to create an Application Segment in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables connection
# to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id. These may be defined as host variables
# (see `host_vars/zpa_cloud.yml` for an example) or extra vars.
#
# Modules Used
# ============
#
# zpa_application_segment - https://willguibr.github.io/zpacloud-ansible/modules/zpa_application_segment.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_application_segment.yml

- hosts: localhost
  connection: local

  tasks:

# Gather Server Group Info
    - name: Gather Server Group Info
      willguibr.zpacloud.zpa_server_group_info:
        name: "All Other Services"
      register: server_group_id

# Gather Segment Group Info
    - name: Gather Segment Group Info
      willguibr.zpacloud.zpa_segment_group_info:
        name: "All Other Services"
      register: segment_group_id

# Create an Application Segment
    - name: Create an Application Segment
      willguibr.zpacloud.zpa_application_segment:
        state: absent
        name: Example Application
        description: Example Application Test
        enabled: true
        health_reporting: ON_ACCESS
        bypass_type: NEVER
        is_cname_enabled: true
        tcp_port_range:
          - from: "80"
            to: "80"
        domain_names:
          - crm1.example.com
          - crm2.example.com
        segment_group_id: "{{ segment_group_id.data[0].id }}"
        server_groups:
          - id: "{{ server_group_id.data[0].id }}"
