---
# zpa_app_connector_groups.yml - Create/Update/Delete an App Connector Group.
#
# Description
# ===========
#
# Quick examples of how to use the 'zpa_app_connector_groups' module to create an App Connector Group in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables for connection to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id
# These may be defined as host variables (see `host_vars/zpa_cloud.yml` for an example) or 
# extra vars.
#
# Modules Used
# ============
#
# zpa_app_connector_groups - https://willguibr.github.io/zpacloud-ansible/modules/zpa_app_connector_groups.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_app_connector_groups.yml

- name: Create ZPA App Connector Groups
  hosts: localhost

  tasks:
  
    - name: Gather Information Details of All Customer Version Profiles
      willguibr.zpacloud.zpa_customer_version_profile_info:
      register: version_profile_id

    - debug:
        msg: "{{ version_profile_id }}"

    - name: Create First App Connector Group Example1
      willguibr.zpacloud.zpa_app_connector_groups:
        name: "Example1"
        description: "Example1"
        enabled: true
        city_country: "California, US"
        country_code: "US"
        latitude: "37.3382082"
        longitude: "-121.8863286"
        location: "San Jose, CA, USA"
        upgrade_day: "SUNDAY"
        upgrade_time_in_secs: "66600"
        override_version_profile: true
        version_profile_id: "{{ version_profile_id.data.0.id }}"
        dns_query_type: "IPV4"

    - name: Create Second App Connector Group Example2
      willguibr.zpacloud.zpa_app_connector_groups:
        name: "Example2"
        description: "Example2"
        enabled: true
        city_country: "New York, US"
        country_code: "US"
        latitude: "40.7128"
        longitude: "74.0060"
        location: "New York, NY, USA"
        upgrade_day: "SUNDAY"
        upgrade_time_in_secs: "66600"
        override_version_profile: true
        version_profile_id: "{{ version_profile_id.data.1.id }}"
        dns_query_type: "IPV4"

    - name: Create Second App Connector Group Example3
      willguibr.zpacloud.zpa_app_connector_groups:
        name: "Example3"
        description: "Example3"
        enabled: true
        city_country: "New York, US"
        country_code: "US"
        latitude: "40.7128"
        longitude: "74.0060"
        location: "New York, NY, USA"
        upgrade_day: "SUNDAY"
        upgrade_time_in_secs: "66600"
        override_version_profile: true
        version_profile_id: "{{ version_profile_id.data.2.id }}"
        dns_query_type: "IPV4"

