---
# zpa_service_edge_groups.yml - Create/Update/Delete a Service Edge Group.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_service_edge_groups' module to create Service Edge Group in ZPA.
#
# This playbook requires proper API credentials to be passed statically or via environment variables connection
# to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id. These may be defined as host variables
# (see `host_vars/zpa_cloud.yml` for an example) or extra vars.
#
# Modules Used
# ============
#
# zpa_service_edge_groups - https://willguibr.github.io/zpacloud-ansible/modules/zpa_service_edge_groups.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_service_edge_groups.yml

- hosts: localhost
  connection: local

  vars:
    service_edge_groups:
      - name: Example
        description: Example
        enabled: true
        city_country: California, US
        country_code: US
        latitude: 37.3382082
        longitude: -121.8863286
        location: San Jose, CA, USA
        upgrade_day: SUNDAY
        upgrade_time_in_secs: 66600
        override_version_profile: true
        version_profile_id: 2

  tasks:
    - name: Create/Update/Delete Service Edge Group
      willguibr.zpacloud.zpa_service_edge_groups:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        enabled: "{{ item.enabled }}"
        city_country: "{{ item.city_country }}"
        country_code: "{{ item.country_code }}"
        latitude: "{{ item.latitude }}"
        longitude: "{{ item.longitude }}"
        location: "{{ item.location }}"
        upgrade_day: "{{ item.upgrade_day }}}"
        upgrade_time_in_secs: "{{ item.upgrade_time_in_secs }}"
        override_version_profile: "{{ item.override_version_profile }}"
        version_profile_id: "{{ item.version_profile_id }}"
      with_items: "{{ service_edge_groups }}"
      tags: service_edge_groups
