---
# zpa_lss_config_controller.yml - Create/Update/Delete a LSS Config Controller.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_lss_config_controller' module to create an LSS Config Controller in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables for connection to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id
# These may be defined as host variables (see `host_vars/zpa_cloud.yml` for an example) or 
# extra vars.
#
# LSS Config Requires One of the following Log Type Format.
# The paramenter `log_type` take one of the following parameters:
# * zpn_trans_log
# * zpn_ast_auth_log
# * zpn_auth_log
# * zpn_ast_comprehensive_stats
# * zpn_http_trans_log
#
# Modules Used
# ============
#
# zpa_lss_config_controller - https://willguibr.github.io/zpacloud-ansible/modules/zpa_lss_config_controller.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_lss_config_controller.yml

- name: LSS Config Controller
  hosts: localhost
  tasks:

# Retrieve App Connector Group ID
    - name: LSS App Connector Group
      zpa_app_connector_groups_info:
        name: "LSS App Connector Group"
      register: lss_app_connector

# Retrieve LSS Log Types Format
    - name: Gather LSS Log types formats
      willguibr.zpacloud.zpa_lss_config_log_types_formats_info:
        log_type: zpn_ast_auth_log
      register: zpn_ast_auth_log

# Create LSS Configuration
    - name: LSS Audit Logs
      willguibr.zpacloud.zpa_lss_config_controller:
        config:
          name: "LSS Audit Logs"
          description: "LSS Audit Logs"
          enabled: true
          lss_host: "192.168.1.1"
          lss_port: "11000"
          format: "{{ zpn_ast_auth_log.data.json }}"
          source_log_type: "zpn_ast_auth_log"
        connector_groups:
          - id: "{{ lss_app_connector.data[0].id }}"

# Retrieve LSS Log Types Format
    - name: Gather LSS Log types formats
      willguibr.zpacloud.zpa_lss_config_log_types_formats_info:
        log_type: zpn_trans_log
      register: zpn_trans_log

# Create LSS Configuration
    - name: LSS User Activity
      zpa_lss_config_controller:
        config:
          name: "LSS User Activity"
          description: "LSS User Activity"
          enabled: true
          lss_host: "192.168.1.1"
          lss_port: "11001"
          format: "{{ zpn_trans_log.data.json }}"
          source_log_type: "zpn_trans_log"
          filter:
            - "ZPN_STATUS_AUTH_FAILED"
            - "ZPN_STATUS_DISCONNECTED"
            - "ZPN_STATUS_AUTHENTICATED"
        connector_groups:
          - id: "{{ lss_app_connector.data[0].id }}"