---
# zpa_machine_group_info.yml - Get details (ID and/or Name) of a machine group resource.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_machine_group_info' module to retrieve a Machine Group details from the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables for connection to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id
# These may be defined as host variables (see `host_vars/zpa_cloud.yml` for an example) or 
# extra vars.
#
# Modules Used
# ============
#
# zpa_machine_group_info - https://willguibr.github.io/zpacloud-ansible/modules/zpa_machine_group_info.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_machine_group_info.yml

- name: Gather Details of All Machine Groups
  hosts: localhost

  tasks:
    - name: Gather Details of All Machine Groups
      willguibr.zpacloud.zpa_machine_group_info:
      register: machine_groups

    - debug:
      msg: "{{ machine_groups }}"

    - name: Gather Details of a Specific Machine Group by Name
      willguibr.zpacloud.zpa_machine_group_info:
        name: "Corp_Machine_Group"
      register: machine_group_name

    - debug:
      msg: "{{ machine_group_name }}"

    - name: Gather Details of a Specific Machine Group by ID
      willguibr.zpacloud.zpa_machine_group_info:
        id: "216196257331282583"
      register: machine_group_id

    - debug:
      msg: "{{ machine_group_id }}"
