---
# zpa_provisioning_key_info.yml - Get details (ID and/or Name) of a Provisioning Key by association type (CONNECTOR_GRP or SERVICE_EDGE_GRP).
#
# Description
# ===========
#
# Quick examples of how to use the 'zpa_provisioning_key_info' module to retrieve  details of a Provisioning Key by association type in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables connection
# to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id. These may be defined as host variables
# (see `host_vars/zpa_cloud.yml` for an example) or extra vars.
#
# Modules Used
# ============
#
# zpa_provisioning_key_info - https://willguibr.github.io/zpacloud-ansible/modules/zpa_provisioning_key.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_provisioning_key_info.yml

# Gather Details of All CONNECTOR_GRP Provisioning Keys

- hosts: localhost
  connection: local

  tasks:

    - name: Gather Details of All CONNECTOR_GRP Provisioning Keys
      willguibr.zpacloud.zpa_provisioning_key_info:
        association_type: "CONNECTOR_GRP"
      register: all_connector_grp_keys

    - name: all_connector_grp_keys
      debug:
        msg: "{{ all_connector_grp_keys }}"

    - name: Gather Details of All CONNECTOR_GRP Provisioning Keys by Name
      willguibr.zpacloud.zpa_provisioning_key_info:
        name: "Example App Connector Group"
        association_type: "CONNECTOR_GRP"
      register: connector_grp_key_name

    - name: connector_grp_key_name
      debug:
        msg: "{{ connector_grp_key_name }}"

    - name: Gather Details of All CONNECTOR_GRP Provisioning Keys by ID
      willguibr.zpacloud.zpa_provisioning_key_info:
        id: "8691"
        association_type: "CONNECTOR_GRP"
      register: connector_grp_key_id

    - name: connector_grp_key_id
      debug:
        msg: "{{ connector_grp_key_id }}"

# Gather Details of All SERVICE_EDGE_GRP Provisioning Keys
- hosts: localhost
  connection: local

  tasks:

    - name: Gather Details of All SERVICE_EDGE_GRP Provisioning Keys
      willguibr.zpacloud.zpa_provisioning_key_info:
        association_type: "SERVICE_EDGE_GRP"
      register: all_edge_grp_key_name

    - name: all_edge_grp_key_name
      debug:
        msg: "{{ all_edge_grp_key_name }}"

    - name: Gather Details of All SERVICE_EDGE_GRP Provisioning Keys by Name
      willguibr.zpacloud.zpa_provisioning_key_info:
        name: "Example Service Edge Group"
        association_type: "SERVICE_EDGE_GRP"
      register: edge_grp_key_name

    - name: edge_grp_key_name
      debug:
        msg: "{{ edge_grp_key_name }}"

    - name: Gather Details of All SERVICE_EDGE_GRP Provisioning Keys by ID
      willguibr.zpacloud.zpa_provisioning_key_info:
        id: "8691"
        association_type: "SERVICE_EDGE_GRP"
      register: edge_grp_key_id

    - name: edge_grp_key_id
      debug:
        msg: "{{ edge_grp_key_id }}"
