---
# zpa_idp_controller_info.yml - Get details (ID and/or Name) of an idp controller resource.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_idp_controller_info' module to retrieve a IdP Controller detail from the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables for connection to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id
# These may be defined as host variables (see `host_vars/zpa_cloud.yml` for an example) or 
# extra vars.
#
# Modules Used
# ============
#
# zpa_idp_controller_info - https://willguibr.github.io/zpacloud_ansible/modules/zpa_idp_controller_info.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_idp_controller_info.yml

- name: Gather Details of All IdP Controllers
  hosts: localhost

  tasks:
    - name: Gather Details of All IdP Controllers
      willguibr.zpacloud_ansible.zpa_idp_controller_info:
      register: idp_controllers

    - debug:
      msg: "{{ idp_controllers }}"

    - name: Gather Details of a Specific IdP Controller by Name
      willguibr.zpacloud_ansible.zpa_idp_controller_info:
        name: User_IdP_Name
      register: idp_name

    - debug:
      msg: "{{ idp_name }}"

    - name: Gather Details of a Specific IdP Controller by ID
      willguibr.zpacloud_ansible.zpa_idp_controller_info:
        id: "216196257331282583"
      register: idp_id

    - debug:
      msg: "{{ idp_id }}"