---
# zpa_provisioning_key.yml - Create/Update/Delete an Provisioning Key.
#
# Description
# ===========
#
# Quick examples of how to use the 'zpa_provisioning_key' module to create an Provisioning Key in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables for connection to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id
# These may be defined as host variables (see `host_vars/zpa_cloud.yml` for an example) or 
# extra vars.
#
# Modules Used
# ============
#
# zpa_provisioning_key - https://willguibr.github.io/zpacloud-ansible/modules/zpa_provisioning_key.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_provisioning_key.yml

- name: Create
  hosts: localhost
  tasks:

    - name: Gather Information Details of All Enrollment Certificates
      willguibr.zpacloud_ansible.zpa_enrollement_certificate_info:
        name: "Connector"
      register: connector_cert_id

    - debug:
        msg: "{{ connector_cert_id.data[0].id}}"

    - name: Gather Information Details of Customer Version Profile Group by Name
      willguibr.zpacloud_ansible.zpa_customer_version_profile_info:
        name: "New Release"
      register: version_profile_id

    - debug:
        msg: "{{ version_profile_id.data[0].id }}"

    - name: Create First App Connector Group Example1
      willguibr.zpacloud_ansible.zpa_app_connector_groups:
        state: "absent"
        name: "Example1"
        description: "Example1"
        enabled: true
        city_country: "California, US"
        country_code: "US"
        latitude: "37.3382082"
        longitude: "-121.8863286"
        location: "San Jose, CA, USA"
        upgrade_day: "SUNDAY"
        upgrade_time_in_secs: "66600"
        override_version_profile: true
        version_profile_id: "{{ version_profile_id.data[0].id}}"
        dns_query_type: "IPV4"
      register: app_connector_group

    - name: Create/Update/Delete App Connector Group Provisioning Key
      willguibr.zpacloud_ansible.zpa_provisioning_key:
        state: "absent"
        name: "App Connector Group Provisioning Key"
        association_type: "CONNECTOR_GRP"
        max_usage: "10"
        enrollment_cert_id: "{{ connector_cert_id.data[0].id }}"
        zcomponent_id: "{{ app_connector_group.data.id }}"
      register: provisioning_key

    - debug:
        msg: "{{ provisioning_key }}"

    # - name: Create/Update/Delete Service Edge Connector Group Provisioning Key
    #   willguibr.zpacloud_ansible.zpa_provisioning_key:
    #     name: "Service Edge Connector Group Provisioning Key"
    #     association_type: "CONNECTOR_GRP"
    #     max_usage: "10"
    #     enrollment_cert_id: 6573
    #     zcomponent_id: 216196257331291903
