---
# zpa_application_segment_info.yml - Get details (ID and/or Name) of a Application Segment.
#
# Description
# ===========
#
# Quick examples of how to use the 'zpa_application_segment_info' module to retrieve  details of an Application Segment in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables for connection to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id
# These may be defined as host variables (see `host_vars/zpa_cloud.yml` for an example) or 
# extra vars.
#
# Modules Used
# ============
#
# zpa_application_segment_info - https://willguibr.github.io/zpacloud_ansible/modules/zpa_application_segment_info.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_application_segment_info.yml

- name: Gather Details of All Application Segments
  hosts: localhost

  tasks:

    - name: Gather Details of All Application Segments
      willguibr.zpacloud_ansible.zpa_application_segment_info:
      register: all_app_segments

    - debug:
        msg: "{{ all_app_segments }}"

    - name: Gather Details of a Specific Application Segments by Name
      willguibr.zpacloud_ansible.zpa_application_segment_info:
        name: "Example Application Segment"
      register: app_segment_name
      
    - debug:
        msg: "{{ app_segment_name }}"

    - name: Gather Details of a Specific Application Segments by ID
      willguibr.zpacloud_ansible.zpa_application_segment_info:
        id: "216196257331291981"
      register: app_segment_id
      
    - debug:
        msg: "{{ app_segment_id }}"