---
# zpa_server_group.yml - Create/Update/Delete a Server Group.
#
# Description
# ===========
#
# Quick example of how to use the 'zpa_server_group' module to create a Server Group in the ZPA Cloud.
#
# This playbook requires proper API credentials to be passed statically or via environment variables connection
# to the ZPA Cloud 'zpa_client_id', 'zpa_client_secret' and zpa_customer_id. These may be defined as host variables
# (see `host_vars/zpa_cloud.yml` for an example) or extra vars.
#
# Modules Used
# ============
#
# zpa_server_group - https://willguibr.github.io/zpacloud-ansible/modules/zpa_server_group.html
#
# Usage
# =====
#
#  $ ansible-playbook zpa_server_group.yml

- name: server group
  hosts: localhost

  tasks:

    - name: Create/Update/Delete a Server Group
      willguibr.zpacloud.zpa_server_group:
        name: "Example Test"
        description: "Example  Test"
        enabled: false
        dynamic_discovery: false
        app_connector_groups:
          - id: "216196257331291924"
        servers:
          - id: "216196257331291921"
        applications:
          - id: "216196257331291981"
