name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.3.1

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Check pipenv cache
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-v3-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-v3-

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Install required collections
        run: pipenv run ansible-galaxy collection install -r collections/requirements.yml

      - name: Run ansible-lint
        run: pipenv run ansible-lint *.yml
